### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ArthurJam** [spjoe/mopidy-ircontrol#3]
Hello,
I can't install this extension from pip.
Do you know how to install this extension from source  ?
Thx

```
/usr/bin/pip run on Fri Sep 25 13:40:47 2015
Downloading/unpacking Mopidy-IRControl

  Getting page http://pypi.python.org/simple/Mopidy-IRControl
  Could not fetch URL http://pypi.python.org/simple/Mopidy-IRControl: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/Mopidy-IRControl when looking for download links for Mopidy-IRControl
  Getting page http://pypi.python.org/simple/
  URLs to search for versions for Mopidy-IRControl:
  * http://pypi.python.org/simple/Mopidy-IRControl/
  Getting page http://pypi.python.org/simple/Mopidy-IRControl/
  Could not fetch URL http://pypi.python.org/simple/Mopidy-IRControl/: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/Mopidy-IRControl/ when looking for download links for Mopidy-IRControl
  Could not find any downloads that satisfy the requirement Mopidy-IRControl

No distributions at all found for Mopidy-IRControl
```

**Comment by jodal** [comment]
I don't think this extension was ever uploaded to PyPI. You can try installing it directly from GitHub:

```
pip install https://github.com/spjoe/mopidy-ircontrol/archive/master.zip
```

**Comment by ArthurJam** [comment]
Thank you for your fast answer.
i follow an other way : 

```
git clone https://github.com/spjoe/mopidy-ircontrol.git
apt-get install liblircclient-dev python-dev pip
pip install pylirc2
python setup.py install
```

The extension has been correctly installed and loaded.
But mopidy dont react to button pressure.

**Comment by ArthurJam** [comment]
I follow the procedure from the other issue : 

```
mopidyctl --save-debug-log
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf --save-debug-log" as user mopidy
X11 connection rejected because of wrong authentication.
INFO     2015-09-25 14:34:00,989 [12129:MainThread] mopidy.__main__
  Starting Mopidy 1.1.1
INFO     2015-09-25 14:34:01,081 [12129:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2015-09-25 14:34:01,093 [12129:MainThread] mopidy.config
  Loading config from /etc/mopidy/mopidy.conf
INFO     2015-09-25 14:34:01,102 [12129:MainThread] mopidy.config
  Loading config from command line options
INFO     2015-09-25 14:34:01,248 [12129:MainThread] mopidy.__main__
  Enabled extensions: mpd, http, stream, m3u, IRControl, softwaremixer, file, local
INFO     2015-09-25 14:34:01,250 [12129:MainThread] mopidy.__main__
  Disabled extensions: none
ERROR    2015-09-25 14:34:01,256 [12129:MainThread] mopidy.__main__
  Extension IRControl failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 145, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg/mopidy_IRControl/__init__.py", line 46, in setup
    from .actor import IRControlFrontend
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg/mopidy_IRControl/actor.py", line 9, in <module>
    from mopidy.utils import process
ImportError: No module named utils
INFO     2015-09-25 14:34:01,630 [12129:MainThread] mopidy.commands
  Starting Mopidy mixer: SoftwareMixer
INFO     2015-09-25 14:34:01,641 [12129:MainThread] mopidy.commands
  Starting Mopidy audio
INFO     2015-09-25 14:34:01,649 [12129:MainThread] mopidy.commands
  Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     2015-09-25 14:34:01,675 [12129:Audio-2] mopidy.audio.actor
  Audio output set to "autoaudiosink"
INFO     2015-09-25 14:34:01,691 [12129:MainThread] mopidy.m3u.playlists
  Loaded 0 M3U playlists from /var/lib/mopidy/playlists
INFO     2015-09-25 14:34:04,534 [12129:MainThread] mopidy.local.library
  Loaded 1194 local tracks using json
INFO     2015-09-25 14:34:04,552 [12129:MainThread] mopidy.commands
  Starting Mopidy core
INFO     2015-09-25 14:34:04,629 [12129:MainThread] mopidy.commands
  Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     2015-09-25 14:34:04,635 [12129:MainThread] mopidy.mpd.actor
  MPD server running at [::]:6600
INFO     2015-09-25 14:34:04,650 [12129:HttpFrontend-10] mopidy.http.actor
  HTTP server running at [::ffff:127.0.0.1]:6680
```

The line line 9 of actor.py is incriminated : "from mopidy.utils import process"

**Comment by jodal** [comment]
`mopidy.utils` was never intended to be used by extensions. In Mopidy 1.1.0 it was renamed to `mopidy.internal` to make this more obvious.

**Comment by ArthurJam** [comment]
Ok. If i change this in source, i dont have this error but a new one.
i think the author of this plugin make mistakes in code source.

Btw thx Jodal.

**Comment by spjoe** [comment]
this plugin was for mopidy 0.19. When I have time, I will adapt it. But it worked for me ;-)
