### ISSUE TITLE
pip installation is not working

### ISSUE THREAD

**Issue by Mebus** [spjoe/mopidy-ircontrol#5]
When I run

<code>
pip install Mopidy-IRControl --upgrade
</code>

I get this error in the log file:

```
-----------------------------------------------------------
/usr/bin/pip run on Sat Oct  3 09:16:25 2015
Getting page http://pypi.python.org/simple/Mopidy-IRControl
Could not fetch URL http://pypi.python.org/simple/Mopidy-IRControl: HTTP Error 404: Not Found
Will skip URL http://pypi.python.org/simple/Mopidy-IRControl when looking for download links for Mopidy-IRControl in /usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg
Getting page http://pypi.python.org/simple/
URLs to search for versions for Mopidy-IRControl in /usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg:
* http://pypi.python.org/simple/Mopidy-IRControl/
Getting page http://pypi.python.org/simple/Mopidy-IRControl/
Could not fetch URL http://pypi.python.org/simple/Mopidy-IRControl/: HTTP Error 404: Not Found
Will skip URL http://pypi.python.org/simple/Mopidy-IRControl/ when looking for download links for Mopidy-IRControl in /usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg
Could not find any downloads that satisfy the requirement Mopidy-IRControl in /usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg

No distributions at all found for Mopidy-IRControl in /usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 920, in prepare_files
    req_to_install, self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for Mopidy-IRControl in /usr/local/lib/python2.7/dist-packages/Mopidy_IRControl-0.1.0-py2.7.egg
```

And the upgrade does not work.

Mebus

**Comment by spjoe** [comment]
Sorry the package is not release and not on pip. please install it manually.

**Comment by spjoe** [comment]
Is now released on pypi https://pypi.python.org/pypi/Mopidy-IRControl/
